from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True, slots=True)
class HelpArticle:
    article_id: str
    section: str
    title: str
    body: str


@dataclass(frozen=True, slots=True)
class FieldHelp:
    explanation: str
    required: str
    correct_example: str
    common_wrong_value: str
    wrong_result: str


def _article(article_id: str, section: str, title: str, body: str) -> HelpArticle:
    return HelpArticle(article_id=article_id, section=section, title=title, body=body)


def _field(
    explanation: str,
    required: str,
    correct_example: str,
    common_wrong_value: str,
    wrong_result: str,
) -> FieldHelp:
    return FieldHelp(
        explanation=explanation,
        required=required,
        correct_example=correct_example,
        common_wrong_value=common_wrong_value,
        wrong_result=wrong_result,
    )


def _concept_body(
    *,
    what: str,
    why: str,
    who: str,
    safe: str,
    example: str,
) -> str:
    return "\n".join(
        (
            f"What it is: {what}",
            f"Why it exists: {why}",
            f"Who should touch it: {who}",
            f"Safe to send to a customer: {safe}",
            f"Example: {example}",
        ),
    )


CONCEPT_TERMS: tuple[HelpArticle, ...] = (
    _article(
        "concept-product-root",
        "Concepts",
        "Product root",
        _concept_body(
            what="The top folder for the product you are protecting.",
            why="SKey Studio uses it as the starting point for scans, configuration, and builds.",
            who="Operators choose it when starting a project; admins may review the layout.",
            safe="Yes, the folder name is usually safe, but do not send its private files.",
            example="C:/Products/InvoiceApp contains src/, assets/, and skey.yaml.",
        ),
    ),
    _article(
        "concept-source-project",
        "Concepts",
        "Source project",
        _concept_body(
            what="The original application files before SKey protection is applied.",
            why="The builder needs these files so it can wrap launchers and encrypt resources.",
            who="Operators select entries; developers decide which files belong in the product.",
            safe="No. Treat source code as internal unless your company approves sharing it.",
            example="A Python folder with app/main.py, or a build folder with report.exe.",
        ),
    ),
    _article(
        "concept-protected-release",
        "Concepts",
        "Protected release",
        _concept_body(
            what="The finished output folder produced by the release builder.",
            why="It contains the wrapped launchers, encrypted files, and runtime metadata.",
            who="Operators build and package it; customers receive only this output.",
            safe="Yes, this is the folder intended for customers after license setup.",
            example="dist/customer-release with the protected executable and runtime files.",
        ),
    ),
    _article(
        "concept-skey-yaml",
        "Concepts",
        "skey.yaml",
        _concept_body(
            what="The configuration file that describes product ids, entries, keys, and policy.",
            why="It lets SKey Studio repeat the same build without guessing settings.",
            who="Operators edit normal product fields; advanced admins manage secret fields.",
            safe="No if it includes private keys or package keys; share a scrubbed copy only.",
            example="skey.yaml lists python_entries, package_id, lease_hours, and key values.",
        ),
    ),
    _article(
        "concept-sprjx",
        "Concepts",
        ".sprjx",
        _concept_body(
            what="The Sentinel-style Python folder project file generated by SKey Studio.",
            why="It records the input folder, output folder, protected Python globs, exclusions, and feature id.",
            who="Operators generate it from the Project page; admins may review it before repeated builds.",
            safe="Usually yes if it contains only paths and globs, but do not include private keys in adjacent files.",
            example="sample_smt1.3.sprjx points from smt-v1.3-exhib to smt-v1.3-exhib-p.",
        ),
    ),
    _article(
        "concept-vendor-public-key",
        "Concepts",
        "Vendor public key",
        _concept_body(
            what="The public half of the signing key pair for your vendor account.",
            why="The runtime uses it to confirm the release was signed by your team.",
            who="Advanced admins create it; operators may paste or load it into configuration.",
            safe="Yes. It is public and can be included in releases and support tickets.",
            example="A base64 value stored as vendor_public_key_b64.",
        ),
    ),
    _article(
        "concept-vendor-private-key",
        "Concepts",
        "Vendor private key",
        _concept_body(
            what="The private half of the signing key pair.",
            why="The builder uses it to sign manifests so customers cannot alter releases.",
            who="Advanced admins only; operators should not copy it unless policy allows it.",
            safe="No. Never send it to customers or put it in a customer release.",
            example="A base64 value stored as build_signing_private_key_b64.",
        ),
    ),
    _article(
        "concept-runtime-pin",
        "Concepts",
        "Runtime pin",
        _concept_body(
            what="A fingerprint of the vendor public key that the runtime expects.",
            why="It prevents a release from trusting a different signing key by accident.",
            who="Advanced admins verify it when changing keys; operators can compare values.",
            safe="Yes. It is a fingerprint, not a secret key.",
            example="A SHA-256 value shown after generating the vendor public key.",
        ),
    ),
    _article(
        "concept-package-key",
        "Concepts",
        "Package key",
        _concept_body(
            what="A 32-byte secret key used to protect package content.",
            why="It keeps protected files unreadable outside the licensed runtime.",
            who="Advanced admins generate and store it; operators should use prepared values.",
            safe="No. Treat it like a password for the protected package.",
            example="A URL-safe base64 value stored as package_kek_b64.",
        ),
    ),
    _article(
        "concept-license-server",
        "Concepts",
        "License server",
        _concept_body(
            what="An optional server-side system for issuing license codes, online activation, lease renewal, and revocation.",
            why="It is useful when you need central control after delivery, such as stopping expired, refunded, or compromised licenses.",
            who="Advanced admins register products, packages, and licenses on it; operators normally use the simpler skey.key flow unless a server deployment is required.",
            safe="No. Server secrets and admin tokens stay on the server. Customers receive only release files, license codes, or offline response files.",
            example="For the current customer-key workflow, you do not need to pre-register the customer on the server before building the release.",
        ),
    ),
    _article(
        "concept-server-kek",
        "Concepts",
        "Server KEK",
        _concept_body(
            what="A server-side key-encryption key used to wrap secrets stored by the server.",
            why="It limits exposure if database rows are copied without server secrets.",
            who="Server admins manage it during license server setup.",
            safe="No. Never send it to customers or place it in a desktop project.",
            example="A deployment secret configured on the license server host.",
        ),
    ),
    _article(
        "concept-admin-wrap-key",
        "Concepts",
        "Admin wrap key",
        _concept_body(
            what="A 32-byte admin key used to wrap exported secrets.",
            why="It lets admins prepare secure bundles without exposing raw secret values.",
            who="Advanced admins generate and rotate it.",
            safe="No. Share only wrapped exports, not the wrap key itself.",
            example="A URL-safe base64 value stored as admin_wrap_key_b64.",
        ),
    ),
    _article(
        "concept-activation-certificate",
        "Concepts",
        "Activation certificate",
        _concept_body(
            what="A signed approval that ties a license to a machine and package.",
            why="The runtime checks it before allowing the original program to run.",
            who="Operators create or import it during activation; support may inspect it.",
            safe="Yes for the intended customer, but do not reuse it for another customer.",
            example="A file returned after online activation or offline approval.",
        ),
    ),
    _article(
        "concept-customer-key",
        "Concepts",
        "skey.key",
        _concept_body(
            what="The customer key file generated with each protected release.",
            why="The runtime reads it from the release root, unwraps the package key, and binds it to the first machine that runs the software.",
            who="Operators send it with the customer release; support checks it when a customer reports license missing.",
            safe="Only for the intended customer. After first run it is bound to that machine and should not be reused elsewhere.",
            example="Place skey.key next to the protected product launcher or model_server.py in the release root.",
        ),
    ),
    _article(
        "concept-client-key-dat",
        "Concepts",
        "client_key.dat",
        _concept_body(
            what="A local runtime file created on the customer machine during activation.",
            why="It helps the runtime prove the same machine is requesting leases later.",
            who="Customers and support should keep it with the installed release.",
            safe="No. Do not email it unless support explicitly asks through a secure channel.",
            example="client_key.dat next to the protected launcher after activation.",
        ),
    ),
    _article(
        "concept-state-dat",
        "Concepts",
        "state.dat",
        _concept_body(
            what="A local runtime file that records activation state and lease timing.",
            why="It lets the runtime know whether the customer can keep running offline.",
            who="Customers and support may preserve it when moving or repairing installs.",
            safe="No. It can reveal license state and should stay on the customer machine.",
            example="state.dat records the last valid online lease time.",
        ),
    ),
    _article(
        "concept-runtime-manifest",
        "Concepts",
        "Runtime manifest",
        _concept_body(
            what="The signed list of protected files, hashes, package ids, and policies.",
            why="The runtime uses it to check that release files have not been changed.",
            who="Operators build it automatically; advanced admins inspect it during support.",
            safe="Yes when it is part of a customer release; do not edit it by hand.",
            example="A manifest that names package_id and package_hash for the release.",
        ),
    ),
    _article(
        "concept-online-lease",
        "Concepts",
        "Online lease",
        _concept_body(
            what="A time-limited approval from the license server.",
            why="It lets the server stop revoked or expired licenses without reinstalling.",
            who="Operators configure lease length; customers receive leases automatically.",
            safe="Yes as runtime traffic, but do not manually copy leases between machines.",
            example="A 24-hour lease renewed while the customer is online.",
        ),
    ),
    _article(
        "concept-revocation",
        "Concepts",
        "Revocation",
        _concept_body(
            what="A server rule that blocks a license, machine, or package.",
            why="It stops compromised, refunded, expired, or replaced installs from running.",
            who="License admins manage revocation; operators should confirm before applying it.",
            safe="Yes to discuss with support, but do not expose internal revocation lists.",
            example="Revoking a stolen laptop machine id blocks future leases for that device.",
        ),
    ),
    _article(
        "concept-offline-activation",
        "Concepts",
        "Offline activation",
        _concept_body(
            what="A file-based activation flow for machines that cannot reach the server.",
            why="It lets customers activate secure machines without direct internet access.",
            who="Operators and support staff exchange request and response files.",
            safe="Yes for the intended customer; do not reuse response files elsewhere.",
            example="Customer sends an offline request file and receives an activation file.",
        ),
    ),
)

TASK_GUIDES: tuple[HelpArticle, ...] = (
    _article(
        "guide-protect-python",
        "Task Guides",
        "Protect a Python project",
        "Select the product root, add the Python entry file, confirm resources, then build.",
    ),
    _article(
        "guide-protect-python-nested",
        "Task Guides",
        "Protect Python files in nested folders",
        "\n".join(
            (
                "Use this when a project stores Python files under many folders, for example "
                "C:/path/to/python-project.",
                "Set the product root to the top folder, not to an inner folder such as core/ or utils/.",
                "On the Project page, scan the folder first, then save the generated skey.yaml config file in the source folder. The default output is a sibling folder ending in -p.",
                "Protected scope should be **/*.py so every nested Python file is encrypted; keep the default exclusions for .venv, venv, tests, and __pycache__.",
                "On the Build page, Project root is the source folder. Config file is the generated skey.yaml. Release output is a new output folder, not the source project folder. If you accidentally paste the source folder there, Studio will move it to Project root and use a sibling -p output folder.",
                "Build the protected release, then run Verify Runtime on the generated product folder.",
                "The build writes skey.key in the release root. Send that file with the protected release, or ask the customer to place it in the release root before first run.",
                "On first run, skey.key binds to that customer's machine code. Later runs require both the same skey.key and a matching machine code; missing skey.key means the runtime will refuse to decrypt.",
                "The source project is not modified. In the generated release, model_server.py remains the runnable file, and model_server_r.py is the encrypted source sidecar. Other protected Python files follow the same *_r.py rule.",
            ),
        ),
    ),
    _article(
        "guide-config-assistant",
        "Task Guides",
        "Use Config Assistant",
        "\n".join(
            (
                "Use Config Assistant when you do not want to hand-edit skey.yaml.",
                "Product ID is the stable internal identifier; Product name is the human-readable name shown in release metadata; Version is the software version.",
                "Startup entry is the Python file the operator normally runs first, such as model_server.py.",
                "Protected scope accepts patterns. **/*.py means all Python files under the project; excluded folders are not encrypted or scanned.",
                "Lease hours controls how long a time-limited customer key remains valid; Offline grace hours controls how long an already approved offline machine may keep running. Select Perpetual license for no expiry date.",
                "Development signing is convenient for testing. A production release should use administrator-managed signing keys before customer delivery.",
            ),
        ),
    ),
    _article(
        "guide-protect-exe",
        "Task Guides",
        "Protect an EXE",
        "Add the EXE entry from the build output folder and include any required data files.",
    ),
    _article(
        "guide-protect-jar",
        "Task Guides",
        "Protect a single JAR or EXE",
        "\n".join(
            (
                "Use this when the product is already compiled and there is no visible source code to encrypt.",
                "On the Build page, put the file path in Project root, for example C:/path/to/product.jar.",
                "Leave Config file empty. Studio will infer the single-file shell settings from the file extension.",
                "Release output defaults to a sibling folder ending in -p, for example product-p.",
                "The protected output contains a same-name launcher, such as product.jar, plus .secure runtime files and skey.key. Do not run or ship the original plaintext file.",
                "Place skey.key in the protected output root before first run. The first run binds it to that machine; later runs check both the key file and machine code.",
            ),
        ),
    ),
    _article(
        "guide-protect-dat",
        "Task Guides",
        "Protect DAT/model files",
        "Add model or DAT files as resource entries so they are encrypted with the package.",
    ),
    _article(
        "guide-build-customer-release",
        "Task Guides",
        "Build a customer release",
        "Confirm product id, package id, entries, and keys, then create the release folder.",
    ),
    _article(
        "guide-create-license-code",
        "Task Guides",
        "Create a license code",
        "Start the license server, create the product and package, then issue a license code.",
    ),
    _article(
        "guide-activate-online",
        "Task Guides",
        "Activate online",
        "Run the protected release where it can reach the server and enter the license code.",
    ),
    _article(
        "guide-activate-offline",
        "Task Guides",
        "Activate offline",
        "Export the customer request file, approve it on the server, then import the response.",
    ),
    _article(
        "guide-diagnose-failed-run",
        "Task Guides",
        "Diagnose a failed customer run",
        "Check the license code, package id, server URL, local state files, and runtime logs.",
    ),
    _article(
        "guide-rebuild-after-code-change",
        "Task Guides",
        "Rebuild after changing code",
        "Rebuild the original app first, then run SKey Studio again to make a new release.",
    ),
)

COMMON_ERROR_ARTICLES: tuple[HelpArticle, ...] = (
    _article(
        "error-runtime-manifest-missing",
        "Common Errors",
        "Runtime manifest missing",
        "Recovery: rebuild the release and confirm the runtime manifest is copied next to the "
        "protected launcher before sending the package to the customer.",
    ),
    _article(
        "error-runtime-manifest-signature-invalid",
        "Common Errors",
        "Runtime manifest signature invalid",
        "Recovery: rebuild with the approved signing key, then replace the full customer "
        "release folder instead of copying only the manifest.",
    ),
    _article(
        "error-license-missing",
        "Common Errors",
        "License missing",
        "Recovery: place skey.key in the protected release root. For server-based deployments, "
        "activate the release with the customer's license code or import the offline activation "
        "response before running the protected app.",
    ),
    _article(
        "error-license-expired",
        "Common Errors",
        "License expired",
        "Recovery: check the license record on the server, extend or renew it if allowed, then "
        "have the customer activate or renew the lease again.",
    ),
    _article(
        "error-clock-rollback",
        "Common Errors",
        "Clock rollback",
        "Recovery: correct the customer machine clock, record the support reason, and renew the "
        "license lease after the time is stable.",
    ),
    _article(
        "error-package-tampered",
        "Common Errors",
        "Package tampered",
        "Recovery: replace the customer folder with a fresh release build; do not edit protected "
        "files or the runtime manifest by hand.",
    ),
    _article(
        "error-decrypt-failed",
        "Common Errors",
        "Decrypt failed",
        "Recovery: confirm the release was built with the matching package key and rebuild the "
        "whole package if any encrypted resource was copied from another release.",
    ),
    _article(
        "error-session-invalid",
        "Common Errors",
        "Session invalid",
        "Recovery: close all running copies, activate again if needed, and ask support to review "
        "local state files if the problem repeats.",
    ),
    _article(
        "error-invalid-base64",
        "Common Errors",
        "Invalid base64 key",
        "Paste the complete base64 value without spaces or quotes.",
    ),
    _article(
        "error-missing-entry",
        "Common Errors",
        "No entry files selected",
        "Add at least one Python, EXE, or JAR entry before building a release.",
    ),
    _article(
        "error-license-refused",
        "Common Errors",
        "License refused",
        "Check the license code, product id, package id, and revocation status.",
    ),
)

SECURITY_RULES: tuple[HelpArticle, ...] = (
    _article(
        "security-private-keys",
        "Security Rules",
        "Keep private keys out of releases",
        "Only public keys and fingerprints belong in customer release folders.",
    ),
    _article(
        "security-test-keys",
        "Security Rules",
        "Use test keys only for test builds",
        "Generate production keys separately and store them in your controlled secret system.",
    ),
)

FAQ_ARTICLES: tuple[HelpArticle, ...] = (
    _article(
        "faq-operators",
        "FAQ",
        "Can operators build without seeing secrets?",
        "Yes. Operator mode can use prepared settings while advanced admins manage secrets.",
    ),
    _article(
        "faq-offline",
        "FAQ",
        "Can customers run offline?",
        "Yes. In the customer-key flow, skey.key is read locally and binds on first run. "
        "Server-based releases can also allow offline grace or offline activation.",
    ),
)

HELP_SECTIONS: dict[str, tuple[HelpArticle, ...]] = {
    "Quick Start": (
        _article(
            "quick-start-build",
            "Quick Start",
            "Build a protected release",
            "\n".join(
                (
                    "You are locking the software, creating a license key, and checking that "
                    "the customer has a valid key before the real code runs.",
                    "Select the Python folder or single JAR/EXE file.",
                    "Generate or load configuration; Python folders use skey.yaml, .sprjx is only a compatible import format, and single-file shells can leave it empty.",
                    "Generate keys or load approved keys from an admin.",
                    "Build protected release after reviewing Python, EXE, JAR, and resource "
                    "entries.",
                    "Keep skey.key in the release root; it is the customer key file read automatically at runtime.",
                    "Start license server only if you need server-based activation and lease checks.",
                    "Server-based mode: Create product/package/license records on the server.",
                    "For the offline customer-key flow, send the release and skey.key to the customer. First run binds it to that machine.",
                    "Run the original command through the protected launcher.",
                ),
            ),
        ),
    ),
    "Concepts": CONCEPT_TERMS,
    "Task Guides": TASK_GUIDES,
    "Common Errors": COMMON_ERROR_ARTICLES,
    "Security Rules": SECURITY_RULES,
    "FAQ": FAQ_ARTICLES,
}

HELP_ARTICLES: dict[str, HelpArticle] = {
    article.article_id: article for articles in HELP_SECTIONS.values() for article in articles
}

FIELD_HELP: dict[str, FieldHelp] = {
    "product_name": _field(
        "Human-readable product name shown to operators and customers.",
        "required",
        "Contoso Analytics",
        "test",
        "Operators cannot tell which product the release belongs to.",
    ),
    "product_id": _field(
        "Stable machine-readable id used by the server and runtime.",
        "required",
        "contoso-analytics",
        "Contoso Analytics!",
        "The server may reject requests that do not match the registered id.",
    ),
    "product_version": _field(
        "Version string for the protected release.",
        "required",
        "2.4.1",
        "latest",
        "Support teams cannot identify exactly which build is installed.",
    ),
    "activation_server_url": _field(
        "HTTPS URL used by the runtime to request activations and leases.",
        "optional",
        "https://licenses.example.com",
        "localhost",
        "Customer machines cannot reach the activation server.",
    ),
    "vendor_public_key_b64": _field(
        "Base64 Ed25519 public key used by the runtime to verify signatures.",
        "required",
        "AAECAwQFBgcICQoLDA0ODxAREhMUFRYXGBkaGxwdHh8",
        "path/to/public.key",
        "The runtime cannot verify the signed release manifest.",
    ),
    "build_signing_private_key_b64": _field(
        "Base64 Ed25519 private key used to sign release metadata.",
        "required",
        "ICEiIyQlJicoKSorLC0uLzAxMjM0NTY3ODk6Ozw9Pj8",
        "the public key value",
        "The builder cannot sign the release, or signs with the wrong key.",
    ),
    "package_kek_b64": _field(
        "Base64 32-byte key used to protect package content keys.",
        "required",
        "MDEyMzQ1Njc4OWFiY2RlZjAxMjM0NTY3ODlhYmNkZWY",
        "short-secret",
        "Release encryption fails because the key is not 32 bytes.",
    ),
    "admin_wrap_key_b64": _field(
        "Base64 32-byte key used for admin-only wrapped exports.",
        "required",
        "YWJjZGVmMDEyMzQ1Njc4OWFiY2RlZjAxMjM0NTY3ODk",
        "password123",
        "Admin exports cannot be unwrapped safely.",
    ),
    "python_entries": _field(
        "Python files or modules that should start through the protected runtime.",
        "optional",
        "app/main.py",
        "the whole virtualenv folder",
        "The release becomes too large or starts from the wrong file.",
    ),
    "exe_entries": _field(
        "Windows executable files that should be wrapped for protected launch.",
        "optional",
        "bin/report.exe",
        "report.exe shortcut",
        "The builder cannot find the executable to protect.",
    ),
    "jar_entries": _field(
        "JAR files that should launch through the protected Java loader.",
        "optional",
        "build/product.jar",
        "src/Main.java",
        "The protected Java application cannot be packaged.",
    ),
    "resource_entries": _field(
        "Data files that must be encrypted and shipped with the release.",
        "optional",
        "assets/model.dat",
        "C:/Users/Alice/Desktop/model.dat",
        "The build is tied to one machine or misses required files.",
    ),
    "feature_codes": _field(
        "Short feature names used to enable licensed capabilities.",
        "optional",
        "reports,export",
        "all features forever",
        "Licenses cannot consistently enable or disable features.",
    ),
    "lease_hours": _field(
        "How long an online approval remains valid before renewal.",
        "optional",
        "24",
        "0",
        "The runtime renews too often or refuses to start.",
    ),
    "offline_grace_hours": _field(
        "How long the runtime may continue after the server is unreachable.",
        "optional",
        "72",
        "-1",
        "Offline customers may be blocked or allowed longer than intended.",
    ),
    "perpetual_license": _field(
        "Whether the generated customer key has no expiry date.",
        "optional",
        "checked",
        "checked for a trial customer",
        "A trial may never expire, or a permanent customer may be stopped too early.",
    ),
    "license_code": _field(
        "Customer license code issued by the activation server.",
        "required",
        "LIC-2026-ACME-001",
        "customer name",
        "Activation fails because the server cannot find the license.",
    ),
    "package_id": _field(
        "Unique id for a protected package registered with the server.",
        "required",
        "pkg-contoso-analytics-2.4.1",
        "latest",
        "Lease and revocation checks may target the wrong package.",
    ),
    "package_hash": _field(
        "SHA-256 hash of the protected package or manifest.",
        "required",
        "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
        "not sure",
        "The server cannot prove the runtime is using the expected package.",
    ),
}


def _zh_concept_body(
    *,
    what: str,
    why: str,
    who: str,
    safe: str,
    example: str,
) -> str:
    return "\n".join(
        (
            f"它是什么：{what}",
            f"为什么需要：{why}",
            f"谁来操作：{who}",
            f"能否发给客户：{safe}",
            f"示例：{example}",
        ),
    )


ZH_CONCEPT_TERMS: tuple[HelpArticle, ...] = (
    _article(
        "concept-product-root",
        "概念解释",
        "产品根目录",
        _zh_concept_body(
            what="你要保护的软件所在的最上层文件夹。",
            why="SKey Studio 会从这里扫描入口文件、资源文件，并生成配置。",
            who="操作员在开始项目时选择；管理员可检查目录结构是否正确。",
            safe="通常只发目录名可以，但不要把里面的源代码或私有文件发出去。",
            example="C:/Products/InvoiceApp 里包含 src/、assets/ 和 skey.yaml。",
        ),
    ),
    _article(
        "concept-source-project",
        "概念解释",
        "源项目",
        _zh_concept_body(
            what="还没有加密保护之前的原始应用文件。",
            why="构建器需要这些文件来包装启动入口并加密资源。",
            who="操作员选择入口；开发人员决定哪些文件属于产品。",
            safe="不能。除非公司明确批准，否则源代码只在内部流转。",
            example="包含 app/main.py 的 Python 目录，或包含 report.exe 的构建输出目录。",
        ),
    ),
    _article(
        "concept-protected-release",
        "概念解释",
        "受保护发行包",
        _zh_concept_body(
            what="构建完成后生成、准备交付客户的输出文件夹。",
            why="里面包含包装后的启动器、加密资源和运行时元数据。",
            who="操作员构建和打包；客户只接收这个目录。",
            safe="可以。这是完成授权设置后交付客户的目录。",
            example="dist/customer-release 中包含受保护 exe 和运行时文件。",
        ),
    ),
    _article(
        "concept-skey-yaml",
        "概念解释",
        "skey.yaml",
        _zh_concept_body(
            what="描述产品编号、入口、密钥和授权策略的配置文件。",
            why="它让每次构建都按同一套设置执行，避免手工猜参数。",
            who="操作员维护普通产品字段；高级管理员维护密钥字段。",
            safe="如果包含私钥或包密钥就不能发送，只能发送已脱敏副本。",
            example="skey.yaml 中包含 python_entries、package_id、lease_hours 和密钥值。",
        ),
    ),
    _article(
        "concept-sprjx",
        "概念解释",
        ".sprjx",
        _zh_concept_body(
            what="SKey Studio 为 Python 文件夹生成的圣天诺风格项目文件。",
            why="记录输入文件夹、输出文件夹、需要加密的 Python 通配符、排除项和 feature id。",
            who="操作员在项目页生成；管理员可在重复构建前复核。",
            safe="通常可以随构建记录保存，但不要把私钥或授权密钥放在同一份对外资料里。",
            example="sample_smt1.3.sprjx 从 smt-v1.3-exhib 指向 smt-v1.3-exhib-p。",
        ),
    ),
    _article(
        "concept-vendor-public-key",
        "概念解释",
        "厂商公钥",
        _zh_concept_body(
            what="厂商签名密钥对里的公开部分。",
            why="运行时用它确认发行包确实由你的团队签名。",
            who="高级管理员生成；操作员可把它粘贴或加载到配置中。",
            safe="可以。它是公开值，可放入发行包和支持工单。",
            example="保存为 vendor_public_key_b64 的 base64 值。",
        ),
    ),
    _article(
        "concept-vendor-private-key",
        "概念解释",
        "厂商私钥",
        _zh_concept_body(
            what="厂商签名密钥对里的私密部分。",
            why="构建器用它签名清单，防止客户篡改发行包。",
            who="只能由高级管理员管理；操作员通常不应复制。",
            safe="不能。绝不能发给客户，也不能放入客户发行包。",
            example="保存为 build_signing_private_key_b64 的 base64 值。",
        ),
    ),
    _article(
        "concept-runtime-pin",
        "概念解释",
        "运行时指纹",
        _zh_concept_body(
            what="运行时预期的厂商公钥指纹。",
            why="防止发行包意外信任另一套签名密钥。",
            who="更换密钥时由高级管理员核对；操作员可对照检查。",
            safe="可以。它只是指纹，不是密钥。",
            example="生成厂商公钥后显示的一段 SHA-256 值。",
        ),
    ),
    _article(
        "concept-package-key",
        "概念解释",
        "包密钥",
        _zh_concept_body(
            what="用于保护包内容密钥的 32 字节秘密值。",
            why="它保证受保护文件离开授权运行时后不可读取。",
            who="高级管理员生成并保存；操作员应使用已准备好的值。",
            safe="不能。把它当作受保护包的密码。",
            example="保存为 package_kek_b64 的 URL 安全 base64 值。",
        ),
    ),
    _article(
        "concept-license-server",
        "概念解释",
        "授权服务器",
        _zh_concept_body(
            what="可选的服务端授权系统，用于发放授权码、在线激活、续租和吊销。",
            why="当你需要交付后集中管控授权时使用，例如停止过期、退款、泄露或被替换设备的授权。",
            who="高级管理员在服务器上登记产品、软件包和授权；如果只是当前 skey.key 客户密钥流程，操作员通常不需要使用服务器。",
            safe="不能。服务器密钥和管理员令牌只留在服务器上；客户只接收发行包、授权码或离线响应文件。",
            example="当前客户密钥流程下，构建发行包前不需要提前在授权服务器注册客户。",
        ),
    ),
    _article(
        "concept-server-kek",
        "概念解释",
        "服务器 KEK",
        _zh_concept_body(
            what="授权服务器用来包裹数据库内秘密值的密钥加密密钥。",
            why="即使数据库行被复制，攻击者也不能直接拿到明文秘密。",
            who="服务器管理员在部署授权服务器时管理。",
            safe="不能。不要发给客户，也不要写入桌面项目。",
            example="配置在授权服务器主机上的部署密钥。",
        ),
    ),
    _article(
        "concept-admin-wrap-key",
        "概念解释",
        "管理员包裹密钥",
        _zh_concept_body(
            what="用于包裹导出秘密值的 32 字节管理员密钥。",
            why="管理员可准备安全导出包，而不暴露原始秘密。",
            who="高级管理员生成和轮换。",
            safe="不能。只能分享被包裹后的导出内容，不能分享这个密钥。",
            example="保存为 admin_wrap_key_b64 的 URL 安全 base64 值。",
        ),
    ),
    _article(
        "concept-activation-certificate",
        "概念解释",
        "激活证书",
        _zh_concept_body(
            what="把授权码、机器和软件包绑定在一起的签名批准文件。",
            why="受保护程序启动前会检查它，确认客户有权运行。",
            who="操作员在线生成或导入；支持人员可检查状态。",
            safe="只能给对应客户使用，不能复制给另一台机器或另一个客户。",
            example="在线激活或离线批准后返回的证书文件。",
        ),
    ),
    _article(
        "concept-customer-key",
        "概念解释",
        "skey.key",
        _zh_concept_body(
            what="每次构建受保护发行包时生成的客户授权文件。",
            why="运行时会从发行包根目录自动读取它，解开软件包密钥，并在第一次运行时绑定当前机器码。",
            who="操作员随客户发行包一起发送；客户提示缺少授权时，支持人员优先检查它是否在根目录。",
            safe="只能给目标客户使用。首次运行后会绑定到该机器，不应复制给其他机器复用。",
            example="把 skey.key 放在受保护启动文件或 model_server.py 所在的发行包根目录。",
        ),
    ),
    _article(
        "concept-client-key-dat",
        "概念解释",
        "client_key.dat",
        _zh_concept_body(
            what="客户机器激活时生成的本地运行时文件。",
            why="运行时用它证明后续续租请求来自同一台机器。",
            who="客户和支持人员应把它保留在安装目录中。",
            safe="不能。除非支持流程明确要求，并且使用安全通道。",
            example="激活后位于受保护启动器旁边的 client_key.dat。",
        ),
    ),
    _article(
        "concept-state-dat",
        "概念解释",
        "state.dat",
        _zh_concept_body(
            what="记录激活状态和租约时间的本地运行时文件。",
            why="它让运行时判断客户离线时是否还能继续运行。",
            who="迁移或维修安装时，客户和支持人员可保留它。",
            safe="不能。它可能暴露授权状态，应留在客户机器上。",
            example="state.dat 记录最后一次有效在线租约时间。",
        ),
    ),
    _article(
        "concept-runtime-manifest",
        "概念解释",
        "运行时清单",
        _zh_concept_body(
            what="受签名保护的文件列表、哈希、包编号和策略说明。",
            why="运行时用它检查发行包文件是否被修改。",
            who="操作员构建时自动生成；高级管理员可在支持时查看。",
            safe="作为客户发行包的一部分可以发送，但不要手工编辑。",
            example="清单中记录 package_id 和 package_hash。",
        ),
    ),
    _article(
        "concept-online-lease",
        "概念解释",
        "在线租约",
        _zh_concept_body(
            what="授权服务器发出的有时间限制的运行批准。",
            why="服务器可在不重新安装的情况下阻止吊销或过期授权。",
            who="操作员配置租约时长；客户联网时自动续租。",
            safe="作为运行时通信可以存在，但不要手工复制给另一台机器。",
            example="客户在线时自动续期的 24 小时租约。",
        ),
    ),
    _article(
        "concept-revocation",
        "概念解释",
        "吊销",
        _zh_concept_body(
            what="服务器上阻止某个授权、机器或软件包继续运行的规则。",
            why="用于处理泄露、退款、过期或更换设备的安装。",
            who="授权管理员管理；操作员执行前应确认原因。",
            safe="可以和支持沟通原因，但不要暴露内部吊销列表。",
            example="吊销被盗笔记本的机器指纹后，该设备无法再续租。",
        ),
    ),
    _article(
        "concept-offline-activation",
        "概念解释",
        "离线激活",
        _zh_concept_body(
            what="面向不能联网机器的文件交换激活流程。",
            why="安全隔离环境也能完成授权，而不需要直接访问服务器。",
            who="操作员和支持人员交换请求文件与响应文件。",
            safe="只能给目标客户使用，不要复用到其他机器。",
            example="客户导出离线请求文件，支持返回离线激活响应文件。",
        ),
    ),
)


ZH_TASK_GUIDES: tuple[HelpArticle, ...] = (
    _article("guide-protect-python", "操作指南", "保护 Python 项目", "选择产品根目录，添加 Python 入口文件，确认资源文件，然后构建。"),
    _article(
        "guide-protect-python-nested",
        "操作指南",
        "加密多级子文件夹中的 Python 文件",
        "\n".join(
            (
                "适用场景：项目里的 Python 文件分散在多级目录中，例如 C:/path/to/python-project。",
                "第 1 步：产品根目录选择最外层项目文件夹，不要选择 core/、utils/ 这类内部子目录。",
                "第 2 步：在项目页先扫描项目，然后保存自动生成的 skey.yaml 配置文件。默认输出目录是源项目旁边的 -p 文件夹。",
                "第 3 步：加密范围保持 **/*.py，这会把所有子文件夹里的 Python 文件都纳入加密；排除目录默认保留 .venv、venv、tests、__pycache__。",
                "第 4 步：构建页里的项目根目录是源项目文件夹；配置文件是刚生成的 skey.yaml；发行包输出目录是新生成目录，不要填源项目目录。如果误填，软件会自动把它改回项目根目录，并使用旁边的 -p 输出目录。",
                "第 5 步：构建受保护发行包，然后对生成的产品目录运行验证运行时，确认运行时清单和文件哈希有效。",
                "第 6 步：构建会在发行包根目录生成 skey.key。把它随发行包发送给客户，或让客户放到发行包根目录后再第一次运行。",
                "第 7 步：第一次运行时 skey.key 会绑定当前机器码；后续运行会同时校验 skey.key 和机器码。缺少 skey.key 时，运行时会拒绝解密。",
                "结果说明：原始项目不会被修改。发行包中 model_server.py 仍然是运行文件，model_server_r.py 是加密后的源码侧车文件；其他 Python 文件同样生成对应的 *_r.py。",
            ),
        ),
    ),
    _article(
        "guide-config-assistant",
        "操作指南",
        "使用配置助手",
        "\n".join(
            (
                "不想手写 skey.yaml 时使用配置助手。",
                "产品 ID 是系统内部稳定标识；产品名称是给人看的名称；版本号填写当前软件版本。",
                "启动入口选择操作员平时最先运行的 Python 文件，例如 model_server.py。",
                "加密范围支持通配符。**/*.py 表示项目下所有 Python 文件；排除目录不会被扫描或加密。",
                "授权时长控制限时客户密钥多久有效；离线宽限控制已经批准的离线机器还能继续运行多久。勾选永久授权表示不设置到期时间。",
                "开发测试签名方便测试。正式交付前应由管理员替换为生产签名密钥。",
            ),
        ),
    ),
    _article("guide-protect-exe", "操作指南", "保护 EXE", "从构建输出目录添加 EXE 入口，并包含运行所需的数据文件。"),
    _article(
        "guide-protect-jar",
        "操作指南",
        "保护单个 JAR 或 EXE",
        "\n".join(
            (
                "适用场景：产品已经编译完成，没有需要逐个加密的源码文件。",
                "在构建页把文件路径填到项目根目录，例如 C:/path/to/product.jar。",
                "配置文件可以留空，软件会根据文件扩展名自动选择单文件套壳方式。",
                "发行包输出默认是旁边的 -p 文件夹，例如 product-p。",
                "输出目录中会有同名启动文件，例如 product.jar、.secure 运行时文件以及 skey.key。不要运行或交付原始明文文件。",
                "首次运行前确认 skey.key 位于受保护输出根目录。第一次运行会绑定机器码，后续运行会同时校验密钥文件和机器码。",
            ),
        ),
    ),
    _article("guide-protect-dat", "操作指南", "保护 DAT/模型文件", "把模型或 DAT 文件作为资源加入，它们会随软件包一起加密。"),
    _article("guide-build-customer-release", "操作指南", "构建客户发行包", "确认 product id、package id、入口和密钥，然后创建发行包目录。"),
    _article("guide-create-license-code", "操作指南", "创建授权码", "启动授权服务器，创建产品、软件包和授权记录，然后签发授权码。"),
    _article("guide-activate-online", "操作指南", "在线激活", "在能访问服务器的机器上运行受保护发行包，并输入客户授权码。"),
    _article("guide-activate-offline", "操作指南", "离线激活", "导出客户请求文件，在服务器侧批准后，再把响应文件导入客户机器。"),
    _article("guide-diagnose-failed-run", "操作指南", "诊断客户无法运行", "检查授权码、package id、服务器地址、本地状态文件和运行时日志。"),
    _article("guide-rebuild-after-code-change", "操作指南", "代码变更后重新构建", "先重新构建原始应用，再用 SKey Studio 生成新的受保护发行包。"),
)


ZH_COMMON_ERROR_ARTICLES: tuple[HelpArticle, ...] = (
    _article("error-runtime-manifest-missing", "常见错误", "缺少运行时清单", "处理：重新构建发行包，并确认运行时清单和受保护启动器一起发送给客户。"),
    _article("error-runtime-manifest-signature-invalid", "常见错误", "运行时清单签名无效", "处理：使用批准的签名密钥重新构建，并替换整个客户发行包，不要只复制清单文件。"),
    _article("error-license-missing", "常见错误", "缺少授权", "处理：先确认 skey.key 位于受保护发行包根目录。服务器模式下，再使用客户授权码激活发行包，或导入离线激活响应。"),
    _article("error-license-expired", "常见错误", "授权已过期", "处理：检查服务器上的授权记录，允许时延长或续期，然后让客户重新激活或续租。"),
    _article("error-clock-rollback", "常见错误", "检测到系统时间回拨", "处理：校正客户机器时间，记录支持原因，并在时间稳定后重新续租。"),
    _article("error-package-tampered", "常见错误", "软件包被篡改", "处理：用新构建的发行包替换客户目录，不要手工修改受保护文件或运行时清单。"),
    _article("error-decrypt-failed", "常见错误", "解密失败", "处理：确认发行包使用匹配的包密钥构建；如果加密资源来自其他发行包，请整体重建。"),
    _article("error-session-invalid", "常见错误", "会话无效", "处理：关闭所有运行中的副本，必要时重新激活；问题重复时请支持人员检查本地状态文件。"),
    _article("error-invalid-base64", "常见错误", "密钥 base64 无效", "粘贴完整 base64 值，不要带空格、引号或换行残片。"),
    _article("error-missing-entry", "常见错误", "没有选择入口文件", "构建发行包前至少添加一个 Python、EXE 或 JAR 入口。"),
    _article("error-license-refused", "常见错误", "授权被拒绝", "检查授权码、product id、package id 和吊销状态是否匹配。"),
)


ZH_SECURITY_RULES: tuple[HelpArticle, ...] = (
    _article("security-private-keys", "安全规则", "私钥不得进入发行包", "客户发行包里只能包含公钥和指纹，不能包含私钥、包密钥或管理员包裹密钥。"),
    _article("security-test-keys", "安全规则", "测试密钥只用于测试构建", "生产密钥应单独生成，并保存在公司认可的秘密管理系统中。"),
)


ZH_FAQ_ARTICLES: tuple[HelpArticle, ...] = (
    _article("faq-operators", "常见问题", "操作员能否在看不到密钥的情况下构建？", "可以。操作员模式使用管理员准备好的设置，高级管理员负责管理秘密值。"),
    _article("faq-offline", "常见问题", "客户能否离线运行？", "可以。客户密钥流程会在本地读取 skey.key，并在第一次运行时绑定机器码。服务器模式也可以使用离线宽限或离线激活。"),
)


ZH_HELP_SECTIONS: dict[str, tuple[HelpArticle, ...]] = {
    "快速开始": (
        _article(
            "quick-start-build",
            "快速开始",
            "构建受保护发行包",
            "\n".join(
                (
                    "你要做的是把软件加锁，创建授权码，并在真正代码运行前检查客户是否有有效授权。",
                    "选择 Python 文件夹，或选择单个 JAR/EXE 文件。",
                    "生成或加载配置；Python 文件夹使用 skey.yaml，.sprjx 只是兼容导入格式，单文件套壳可以留空。",
                    "生成测试密钥，或加载管理员批准的生产密钥。",
                    "检查 Python、EXE、JAR 和资源条目后，构建受保护发行包。",
                    "保留发行包根目录中的 skey.key；运行时会自动读取这个客户密钥文件。",
                    "只有需要服务器模式激活和租约检查时，才启动授权服务器。",
                    "服务器模式下，在服务器上创建产品、软件包和授权记录。",
                    "服务器模式仍可使用客户授权码激活发行包。",
                    "离线客户密钥流程下，把发行包和 skey.key 发送给客户，第一次运行会绑定该机器。",
                    "通过受保护启动器运行原始程序。",
                ),
            ),
        ),
    ),
    "概念解释": ZH_CONCEPT_TERMS,
    "操作指南": ZH_TASK_GUIDES,
    "常见错误": ZH_COMMON_ERROR_ARTICLES,
    "安全规则": ZH_SECURITY_RULES,
    "常见问题": ZH_FAQ_ARTICLES,
}


ZH_FIELD_HELP: dict[str, FieldHelp] = {
    "product_name": _field("给操作员和客户看的产品名称。", "必填", "Contoso Analytics", "test", "操作员无法判断发行包属于哪个产品。"),
    "product_id": _field("服务器和运行时使用的稳定机器可读编号。", "必填", "contoso-analytics", "Contoso Analytics!", "服务器可能拒绝与注册编号不匹配的请求。"),
    "product_version": _field("受保护发行包的版本号。", "必填", "2.4.1", "latest", "支持人员无法准确判断客户安装的是哪个构建。"),
    "activation_server_url": _field("运行时请求激活和租约的 HTTPS 地址。", "可选", "https://licenses.example.com", "localhost", "客户机器无法访问激活服务器地址。"),
    "vendor_public_key_b64": _field("运行时用来验证签名的 Base64 Ed25519 公钥。", "必填", "AAECAwQFBgcICQoLDA0ODxAREhMUFRYXGBkaGxwdHh8", "path/to/public.key", "运行时无法验证已签名的发行包清单。"),
    "build_signing_private_key_b64": _field("构建器用于签名发行包元数据的 Base64 Ed25519 私钥。", "必填", "ICEiIyQlJicoKSorLC0uLzAxMjM0NTY3ODk6Ozw9Pj8", "公钥值", "构建器无法签名，或使用错误密钥签名。"),
    "package_kek_b64": _field("用于保护包内容密钥的 Base64 32 字节密钥。", "必填", "MDEyMzQ1Njc4OWFiY2RlZjAxMjM0NTY3ODlhYmNkZWY", "short-secret", "密钥不是 32 字节会导致发行包加密失败。"),
    "admin_wrap_key_b64": _field("管理员导出秘密时使用的 Base64 32 字节包裹密钥。", "必填", "YWJjZGVmMDEyMzQ1Njc4OWFiY2RlZjAxMjM0NTY3ODk", "password123", "管理员导出内容无法安全解包。"),
    "python_entries": _field("需要通过受保护运行时启动的 Python 文件或模块。", "可选", "app/main.py", "整个 virtualenv 文件夹", "发行包会过大，或从错误文件启动。"),
    "exe_entries": _field("需要包装启动的 Windows 可执行文件。", "可选", "bin/report.exe", "report.exe 快捷方式", "构建器找不到要保护的可执行文件。"),
    "jar_entries": _field("需要通过受保护 Java 加载器启动的 JAR 文件。", "可选", "build/product.jar", "src/Main.java", "Java 应用无法正确打包。"),
    "resource_entries": _field("必须加密并随发行包交付的数据文件。", "可选", "assets/model.dat", "C:/Users/Alice/Desktop/model.dat", "构建会绑定到一台机器，或遗漏必要文件。"),
    "feature_codes": _field("用于开启授权功能的短功能名。", "可选", "reports,export", "all features forever", "授权无法稳定开启或关闭功能。"),
    "lease_hours": _field("在线批准在续租前保持有效的小时数。", "可选", "24", "0", "运行时会过于频繁续租，或拒绝启动。"),
    "offline_grace_hours": _field("服务器不可达后运行时可继续离线运行的小时数。", "可选", "72", "-1", "离线客户可能被错误阻止，或被允许过久。"),
    "perpetual_license": _field("生成的客户密钥是否没有到期时间。", "可选", "勾选", "试用客户也勾选", "试用授权可能永不过期，或永久客户被过早阻止。"),
    "license_code": _field("激活服务器签发给客户的授权码。", "必填", "LIC-2026-ACME-001", "客户名称", "服务器找不到授权记录，激活会失败。"),
    "package_id": _field("在服务器上注册的受保护软件包唯一编号。", "必填", "pkg-contoso-analytics-2.4.1", "latest", "租约和吊销检查可能命中错误软件包。"),
    "package_hash": _field("受保护软件包或清单的 SHA-256 哈希。", "必填", "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855", "not sure", "服务器无法证明运行时使用的是预期软件包。"),
}


def get_help_sections(language: str) -> dict[str, tuple[HelpArticle, ...]]:
    if language == "zh-CN":
        return ZH_HELP_SECTIONS
    return HELP_SECTIONS


def get_help_articles(language: str) -> dict[str, HelpArticle]:
    return {
        article.article_id: article
        for articles in get_help_sections(language).values()
        for article in articles
    }


def get_field_help(language: str) -> dict[str, FieldHelp]:
    if language == "zh-CN":
        return ZH_FIELD_HELP
    return FIELD_HELP
